// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkvxzxvbchafjsjbmvlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indrdnh6eHZiY2hhZmpzamJtdmx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTI0MzQsImV4cCI6MjA2ODA4ODQzNH0.WuBnxybff5ccLu4oBBVUfGJ659VwmguYme8K8AeGgII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});